### ISSUE TITLE
ImportError doesn't provide the name of the file that failed import in the exception information

### ISSUE THREAD

**Issue by YPCrumble** [nose-devs/nose2#498] opened 2021-05-14 14:02 UTC
Thanks for maintaining nose2!

I recently came across an issue where I had a circular import in my code that was broken on CI but not my local machine. The code was raising an `ImportError` with a vague error message:

> ImportError: No module named ModuleImportFailure

The code in question catches failed imports: https://github.com/nose-devs/nose2/blob/master/nose2/util.py#L165

It would be nice to include _which_ file raised the exception to make pinpointing the source of the error easier. Something like this idea:

```

class Nose2ImportError(ImportError):
    pass

...

        try:
            module = __import__('.'.join(splitted_name))
            break
        except:
            t, v, tb = sys.exc_info()
            del splitted_name[-1]
            if not splitted_name:
                if t is ImportError:
                    # This is a regular ImportError, include the splitted_name variable to help with debugging.
                    import_error_with_splitted_name = Nose2ImportError("Import error in %s" % splitted_name) from v
                    six.reraise(t, import_error_with_splitted_name, tb)
               six.reraise(t, v, tb)
```

The code above would raise a `Nose2ImportError` including a helpful error message in the event that the error is a regular import error. Otherwise would behave as it does currently.

Please let me know if a PR would be welcomed, and thanks again for maintaining Nose2!!!

**Comment by YPCrumble** [comment] 2021-10-12 13:50
Thanks @sirosen - I no longer have access to the codebase I was working on for this so won't be able to make the PR.

I really enjoyed using nose2 however - the availability of the API was instrumental to getting our test suite up and running at my last job. Thanks for maintaining it!

**Comment by sirosen** [comment] 2022-07-16 06:50
I just did a bunch of tooling around with this to try to reproduce, with a few circular import cases like the OP's initial post mentioned, and I was not able to reproduce this issue.

As such, I'm going to close this as a CNR.
It's a reminder for me in always making sure to ask promptly for a MWE when bugs come in.

If anyone comes across this and has a reproducer, I'm more than happy to reopen it.
But I don't want to make changes without a well-identified bug we're trying to fix.

**Closed by sirosen** 2022-07-16 06:50 UTC
Labels: feature

**Comment by YPCrumble** [comment] 2022-07-16 12:12
Makes sense @sirosen - the only other thing I can add is that this was passing on my MacBook and failing on CircleCI which was using linux. But makes sense - I wouldn't be able to reproduce either at this point.
